# Generated by Django 4.1.5 on 2023-02-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_services_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='meta',
        ),
        migrations.AlterField(
            model_name='blog',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
