# Generated by Django 4.1.5 on 2023-02-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_blog_meta_alter_blog_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
